from Layer import Tensor, Convolution2D, Flatten,Dense
import numpy as np
Input = Tensor(3,4,4)
input = np.random.rand(3,4,4)
print(input)
# 正则化
cv2Dout = Convolution2D(filters=3,kernel=(3,3),activation='relu')(Input)
# print(cv2Dout.get_layer())
shapeA = cv2Dout.get_layer()
shapeA = list(shapeA)
# print(shapeA)
fed = np.ones(shapeA)
print(fed)
layer = cv2Dout.getHiddenLayer()
cv2Dres = layer[0].forward(input)
feedback = layer[0].feedBackward(fed)
# print("cv2Dres:\n",cv2Dres)
# print("feedback:\n",feedback)
flatOut = Flatten()(cv2Dout)
print("flatOut:\n",list(flatOut.get_layer()))
layer = flatOut.getHiddenLayer()
flatRes = layer[-1].forward(cv2Dres)
print("cv2Dres:\n",cv2Dres)
print("flatOut:\n", flatRes)
softmaxOut = Dense(neurons=12,activation="softmax")(flatOut)
layer = softmaxOut.getHiddenLayer()
softRes = layer[-1].forward(flatRes)
print("softOut:\n", softRes)